# Uncomment the next line to define a global platform for your project
 platform :ios, '11.1'

target 'RichPushNotificationsDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  # Pods for RichPushNotificationsDemo
  target 'NotificationService' do
    pod 'ReachabilitySwift'
  end
end
